$ANSIBLE_VAULT;1.1;AES256
32666561343265343963333837323738336663323338326139343531393464646130306362373065
6637306539386261373134313438333334363530363030360a646334656636613162313333346335
66663736663233636664373137336661353333363063353166353837386263326263663437353739
6335613834303464350a386639343361386435366434663666663837393233373365306433646261
35656437383437653439373362623361343635313335613439343831363539623739316238333332
30356465663339353461383237333163653134396465303637313363373865363333633264653864
36383666333362626434343939633139653538666437366464633034336563633031383838653266
61353062633034383739643834386563613431353234656530323432376530363430303162663137
6666